## 端口号
server:
  port: 8080
## 应用名
spring:
  # 配置Druid数据源类型
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据库连接URL，包括数据库名、允许的公开密钥检索、字符编码、禁用SSL、时区设置等
    url: jdbc:mysql://8.140.197.151:3306/leisure_inn?allowPublicKeyRetrieval=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull
    # 数据库用户名
    username: root
    # 数据库密码
    password: posin@1998
    # 数据库驱动类名
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Redis数据库索引
  redis:
    database: 0
    # Redis连接超时时间（毫秒）
    timeout: 1800000
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器端口
    port: 6379
    # Redis服务器连接密码
    password: xxx


